### ISSUE TITLE
Tetris controls moving page

### ISSUE THREAD

**Issue by Heroshane1** [chrisseals98/BOBBY#21]
New Tetris page is moving when keys are pressed (up, down, space)

Started happening upon merging of branches before release. (likely something was overwritten due to merge conflict. 

To replicate this error go into the Tetris game, ensure you are within the Tetris game canvas, and press the space bar, up arrow, or down arrow. This will cause the page to scroll.

**Comment by kylew1208** [comment]
Fixed in Tetris-spacebar-bug-fix branch
