### ISSUE TITLE
Tetris quickdrop broken

### ISSUE THREAD

**Issue by Heroshane1** [chrisseals98/BOBBY#22]
Pressing space when playing Tetris no longer drops the Tetronimo. It instead scrolls the page as before
This is also likely due to changes made fixing merge conflicts

To replicate this error go into the Tetris game, ensure you are within the Tetris game canvas, and press the space bar. This will cause the page to scroll and not quickly drop the tetramino.

**Comment by kylew1208** [comment]
Fixed in Tetris-spacebar-bug-fix branch
